
server:
  port: 80

#celilinurls:
#  urun: ${urun_save}
#    save: ${urun_update}
#    update:
#    delete:
#    findall:
#  musteri:
#    save:


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/EgitimTekrar
    username: postgres
    #username: ${POSTGRE_USER}
    password: 123456
    #password: ${POSTGRE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true


